# Generated by Django 5.2.3 on 2025-06-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(),
        ),
    ]
